// Reviewed drone candidates from the original city audit and subsequent destination research.
// Only IDs with accessible YouTube metadata and a clear destination match are enabled.
// New candidates were checked against YouTube oEmbed metadata before being added.
// Unreviewed destinations intentionally have no Drone mode until a suitable video is validated.
window.DRONE_CATALOG = {
  "Sao Paulo": [{ id: "H_JV9XnqAm4", start: 0, confidence: "A" }],
  "Abu Dhabi": [{ id: "_5CSitKheXQ", start: 0, confidence: "A" }],
  "Amsterdam": [{ id: "Oxv6IRcuNaI", start: 0, confidence: "A" }],
  "Ankara": [{ id: "UtKPSDFo3ok", start: 0, confidence: "A" }],
  "Antalya": [{ id: "yT4VnphfDXc", start: 0, confidence: "A" }],
  "Athens": [{ id: "rUes9SGHEz8", start: 0, confidence: "A" }],
  "Atlanta": [{ id: "tcfw_vHcA4U", start: 0, confidence: "A" }],
  "Auckland": [{ id: "0Udu8L68lYw", start: 0, confidence: "B" }],
  "Austin": [{ id: "M3dhlboim9E", start: 0, confidence: "A" }],
  "Baltimore": [{ id: "jgAOXdydq5M", start: 0, confidence: "A" }],
  "Bangalore": [{ id: "eEr56MfFP6I", start: 0, confidence: "A" }],
  "Barcelona": [{ id: "0cHbqAIw4zc", start: 0, confidence: "A" }],
  "Beijing": [{ id: "nXovmcgHKec", start: 0, confidence: "B" }],
  "Belo Horizonte": [{ id: "T9q10nGN0-c", start: 0, confidence: "A" }],
  "Berlin": [{ id: "SO9tUbxIIWU", start: 0, confidence: "A" }],
  "Boston": [{ id: "jDxz4GG2LiM", start: 0, confidence: "A" }],
  "Brasilia": [{ id: "859Wg4tOeok", start: 0, confidence: "A" }],
  "Budapest": [{ id: "ukNpq1cLsCk", start: 0, confidence: "A" }],
  "Buenos Aires": [{ id: "oTDXnAXw66Y", start: 0, confidence: "A" }],
  "Cairo": [{ id: "uz23AE-oemU", start: 0, confidence: "A" }],
  "Chennai": [{ id: "f43q0qi25VU", start: 0, confidence: "B" }],
  "Chicago": [{ id: "3pvlPyoK1cg", start: 0, confidence: "A" }],
  "Dallas": [{ id: "mhkh5PySehY", start: 0, confidence: "B" }],
  "Delhi": [{ id: "l-5rGi8_A_4", start: 0, confidence: "A" }],
  "Detroit": [{ id: "dAfGVGox7KI", start: 0, confidence: "A" }],
  "Dubai": [{ id: "EnT8nqH523Q", start: 0, confidence: "B" }],
  "Edinburgh": [{ id: "RGySRonWwFA", start: 0, confidence: "A" }],
  "Frankfurt": [{ id: "V2wofDTu48g", start: 0, confidence: "A" }],
  "Hamburg": [{ id: "n-K_3Mxx2_0", start: 0, confidence: "A" }],
  "Houston": [{ id: "cnoPHrfH4Yg", start: 0, confidence: "A" }],
  "Istanbul": [{ id: "TUhDzKgdrGU", start: 0, confidence: "A" }],
  "Jakarta": [{ id: "MTPpm6ZF1Io", start: 0, confidence: "A" }],
  "Kuala Lumpur": [{ id: "XVzuVXgbnwY", start: 0, confidence: "A" }],
  "Lisbon": [{ id: "hWRmyqrq2MM", start: 0, confidence: "A" }],
  "London": [{ id: "G5V4wBjR880", start: 0, confidence: "A" }],
  "Los Angeles": [{ id: "vGGL7X_s4AQ", start: 0, confidence: "A" }],
  "Manila": [{ id: "wWYK6IVszPk", start: 0, confidence: "A" }],
  "Melbourne": [{ id: "gutc9lcTtoQ", start: 0, confidence: "A" }],
  "Mexico City": [{ id: "vUKaK_BWtWs", start: 0, confidence: "A" }],
  "Miami": [{ id: "jDPMOwIy0w8", start: 0, confidence: "B" }],
  "Milan": [{ id: "r3oYIZe0FEk", start: 0, confidence: "A" }],
  "Moscow": [{ id: "1gND3LB5zGQ", start: 0, confidence: "A" }],
  "Mumbai": [{ id: "afDUnE-a-us", start: 0, confidence: "A" }],
  "Munich": [{ id: "Cwjv4HQ-pd0", start: 0, confidence: "B" }],
  "Oslo": [{ id: "g24W1eitqVE", start: 0, confidence: "B" }],
  "Paris": [{ id: "wroGPb4-3yM", start: 0, confidence: "A" }],
  "Philadelphia": [{ id: "aRLgZkUDWYY", start: 0, confidence: "B" }],
  "Prague": [{ id: "Qosh3V4wsOI", start: 0, confidence: "B" }],
  "Rio De Janeiro": [{ id: "fA7kQn-l6T4", start: 0, confidence: "A" }],
  "Rome": [{ id: "2ys9ree4sBM", start: 0, confidence: "A" }],
  "Seoul": [{ id: "7JU64bicAsw", start: 0, confidence: "A" }],
  "Singapore": [{ id: "NNsOihnkVAs", start: 0, confidence: "A" }],
  "Stuttgart": [{ id: "l599zrYYjUw", start: 0, confidence: "B" }],
  "Sydney": [{ id: "Yc7r_bbt00M", start: 0, confidence: "A" }],
  "Taipei": [{ id: "yyttxJz1p4w", start: 0, confidence: "A" }],
  "Tampa": [{ id: "Ee2AdCPWOW0", start: 0, confidence: "A" }],
  "Tel Aviv": [{ id: "59aJswKv2DI", start: 0, confidence: "B" }],
  "Tokyo": [{ id: "X2aY-HgWjzg", start: 0, confidence: "A" }],
  "Toronto": [{ id: "znbYbNlymYs", start: 0, confidence: "A" }],
  "Washington DC": [{ id: "qHCMjr-ezu4", start: 0, confidence: "A" }],
  "Bali": [{ id: "Lm9ZxasfHh0", start: 0, confidence: "A" }],
  "Lombok": [{ id: "gbAwtZBKLcg", start: 0, confidence: "A" }],
  "Nusa Penida": [{ id: "8XG_ObGmgC0", start: 0, confidence: "B" }],
  "Gili Islands": [{ id: "4TUGQD3BpN0", start: 0, confidence: "B" }],
  "Komodo": [{ id: "cGb_Ydx37WE", start: 0, confidence: "A" }],
  "Raja Ampat": [{ id: "p1xdVKuO1N8", start: 0, confidence: "A" }],
  "Sumba": [{ id: "J1gz8EpZ5PY", start: 0, confidence: "A" }],
  "Acapulco": [{ id: "tS3XJoZ8JnM", start: 0, confidence: "A" }],
  "Ahmedabad": [{ id: "xdZFacSYPBE", start: 0, confidence: "A" }],
  "Anchorage": [{ id: "4UCpDgJMbUo", start: 0, confidence: "A" }],
  "Brisbane": [{ id: "FXr_RMch1Yg", start: 0, confidence: "A" }],
  "Cape Town": [{ id: "69DzEF_RAcA", start: 0, confidence: "A" }],
  "Denver": [{ id: "wbaDXXofyds", start: 0, confidence: "A" }],
  "Dublin": [{ id: "WTdq5yjKcqg", start: 0, confidence: "A" }],
  "Fortaleza": [{ id: "-jLXO0fd2Tk", start: 0, confidence: "A" }],
  "Havana": [{ id: "hGg92N5-oM8", start: 0, confidence: "A" }],
  "Hawaii": [{ id: "QRvNJX4SqcQ", start: 0, confidence: "A" }],
  "Jaipur": [{ id: "GYuAbHKrV0A", start: 0, confidence: "A" }],
  "Johannesburg": [{ id: "jU8sQWkPLvA", start: 0, confidence: "A" }],
  "Madrid": [{ id: "w7VFfwZYeG4", start: 0, confidence: "A" }],
  "New Orleans": [{ id: "A14iV1uVSSg", start: 0, confidence: "A" }],
  "New York City": [{ id: "7dnLjw9dBCk", start: 0, confidence: "B" }],
  "San Francisco": [{ id: "oLdr80iDFsc", start: 0, confidence: "A" }],
  "Seattle": [{ id: "FnZ9uYWuk-Q", start: 0, confidence: "A" }],
  "Sofia": [{ id: "ctpOAWZqtQg", start: 0, confidence: "A" }],
  "Stockholm": [{ id: "GLdo5PX_UrI", start: 0, confidence: "A" }],
  "Valencia": [{ id: "mWTDKXzOyg0", start: 0, confidence: "A" }],
  "Vancouver": [{ id: "WbfjRoQVZSw", start: 0, confidence: "A" }],
  "Vienna": [{ id: "_8D2ukmn0cs", start: 0, confidence: "A" }],
  "Warsaw": [{ id: "FcjeOHCLaDQ", start: 0, confidence: "A" }],
  "Zurich": [{ id: "4XceEfga_Fo", start: 0, confidence: "A" }],
  "Granada": [{ id: "c6u22gDXtYw", start: 0, confidence: "A" }]
};
