// Curated aerial and drone videos for the cities in the YouCity catalog.
// IDs are kept separate from the main catalog so the original ride sources
// remain unchanged and can be updated independently.
window.DRONE_CATALOG = {
  "Sao Paulo": ["phPgZC9_QhQ"],
  "Abu Dhabi": ["_5CSitKheXQ"],
  "Acapulco": ["5EY1C6GOns8"],
  "Ahmedabad": ["xdZFacSYPBE"],
  "Albuquerque": ["ANzrxcIL7wk"],
  "Amritsar": ["K7YEU8zM2XQ"],
  "Amsterdam": ["Oxv6IRcuNaI"],
  "Anchorage": ["Z7OS5fJ1KKE"],
  "Angeles City": ["9mdIPZw3QSU"],
  "Ankara": ["IaP_4Fb6wLE"],
  "Antalya": ["sUcXpoiASxU"],
  "Asheville": ["p1yh56bezFY"],
  "Aspen": ["2NfW4uVRd9Y"],
  "Athens": ["qSOEAOejr2Q"],
  "Atlanta": ["tcfw_vHcA4U"],
  "Atlantic City": ["oCkRSLwDv_c"],
  "Auckland": ["LdjJWYf6dbc"],
  "Austin": ["n90SxzRa28c"],
  "Bacolod": ["oXO1uhot8IU"],
  "Baguio": ["fAt1kH3Zt80"],
  "Baltimore": ["1szUN8s3Fc0"],
  "Bangalore": ["_YltHpZ1MrI"],
  "Barcelona": ["FGRvP8eoPdw"],
  "Basel": ["OA90pz3n6kE"],
  "Beijing": ["Yr9LK4rwHM4"],
  "Belém": ["VCK37PewzbE"],
  "Belfast": ["PnUVZXq4p8c"],
  "Belo Horizonte": ["T9q10nGN0-c"],
  "Berlin": ["4SGLxZnqYIg"],
  "Beverly Hills": ["b58rfNbU6jg"],
  "Bhopal": ["n-DbqB4iNrU"],
  "Bhubaneswar": ["aqQ6W8DqTIk"],
  "Bordeaux": ["_DMkPTDGOao"],
  "Boston": ["KpGoFvyTuIY"],
  "Brasilia": ["X-FXTAakciw"],
  "Brisbane": ["wqv1-jjNzWs"],
  "Bristol": ["eLvu9EFkcG4"],
  "Bronx": ["pN0H9gLIHg8"],
  "Brooklyn": ["fJrQKki6Xpk"],
  "Budapest": ["lJV9CUafrNg"],
  "Buenos Aires": ["5sFHO-oLC0U"],
  "Cairo": ["uz23AE-oemU"],
  "Campinas": ["DRhFr6BlkZU"],
  "Cancun": ["oMEJSBKcziU"],
  "Cape Town": ["U3czifeJuoY"],
  "Cebu City": ["Ki8-2f4hiAU"],
  "Chandigarh": ["-1h_t9op_rk"],
  "Charleston": ["zRQJXTqSaMA"],
  "Chennai": ["f43q0qi25VU"],
  "Chicago": ["3pvlPyoK1cg"],
  "Cincinnati": ["6uPsNS69P2A"],
  "Cleveland": ["_vcvsSAiqi0"],
  "Columbus": ["cV9L1_Edeg4"],
  "Curitiba": ["jW9rMXgFxro"],
  "Dakar": ["LuB05G98pCA"],
  "Dallas": ["JBsp0o4aJQw"],
  "Davos": ["tr_SWK6ZDBM"],
  "Delhi": ["kxoshFAPX7k"],
  "Denver": ["Mx7zjqeZXrY"],
  "Detroit": ["Ia7pJw1alOY"],
  "Dubai": ["oOoDvZRM1Lk"],
  "Dublin": ["EX5GH8mMROk"],
  "Dunedin": ["iXHqULeYl1Y"],
  "Edinburgh": ["xzBuUxBhASQ"],
  "Faisalabad": ["ID5B8vpojbs"],
  "Fortaleza": ["ZlHmjgSEzIk"],
  "Frankfurt": ["PQ3USMvf6Z8"],
  "General Santos City": ["NYPaeC-1aY8"],
  "Geneva": ["e58DKJUDfPo"],
  "Goa": ["u8vgfFvTcIE"],
  "Gold Coast": ["VRwyFx5CqNI"],
  "Guadalajara": ["gFANFTYrPRg"],
  "Guatemala": ["Dqvwst9puhQ"],
  "Guwahati": ["mq-ENX8-9LM"],
  "Hamburg": ["h8Equ8dSRGI"],
  "Havana": ["hGg92N5-oM8"],
  "Hawaii": ["9EuBryrGU-g"],
  "Hollywood": ["lkHuHU3g57o"],
  "Houston": ["SeSyzyGF_sg"],
  "Hyderabad": ["l0bwtJZmGYs"],
  "Ibiza": ["kx4nxP9UkMY"],
  "Indianapolis": ["JvcwZb_drA8"],
  "Innsbruck": ["_1Lrdy5Alac"],
  "Islamabad": ["ptqMR21mMB0"],
  "Istanbul": ["DdtzYaIUWrc"],
  "Izmir": ["5iYvbT-FPzY"],
  "Jacksonville": ["o3PpMA16kOQ"],
  "Jaipur": ["5JfXkSG6BRo"],
  "Jakarta": ["RseCJxrgWH0"],
  "João Pessoa": ["HPKnPfAG1og"],
  "Johannesburg": ["PnJKV9vSvQQ"],
  "Karachi": ["LvVGFHgRi_Y"],
  "Kochi": ["ZglsiZMQr84"],
  "Kolkata": ["v4i2bF99WqA"],
  "Kuala Lumpur": ["yl-PPjNvOzQ"],
  "Kyiv": ["TYfYX0ngLkE"],
  "La Romana": ["q7OD9Efrwt4"],
  "Lahore": ["CXx5zKmjr80"],
  "Las Vegas": ["_PV6VuhHu7Q"],
  "Lauterbrunnen": ["vIM3WEFcIOw"],
  "Lisbon": ["hWRmyqrq2MM"],
  "Liverpool": ["zFs-MQUiOlY"],
  "Ljubljana": ["-JhCNbM8RVs"],
  "London": ["G5V4wBjR880"],
  "Los Angeles": ["xLNHsEGZ3nM"],
  "Lyon": ["qU3MXhQaVQI"],
  "Madrid": ["w7VFfwZYeG4"],
  "Makati": ["5q7LOZmSbSM"],
  "Manila": ["wWYK6IVszPk"],
  "Melbourne": ["JidUIjTELUE"],
  "Metro Manila": ["wWYK6IVszPk"],
  "Mexico City": ["L6BrmYdowZw"],
  "Miami": ["Dmhws_sBEic"],
  "Milan": ["FL3rmYPZaMw"],
  "Minneapolis": ["09eeU1BPWzY"],
  "Monaco": ["leJyhcQVYho"],
  "Monterrey": ["oGrtpwN84uU"],
  "Montevideo": ["-W5J0B_acT0"],
  "Moscow": ["S_dfq9rFWAE"],
  "Mumbai": ["0ckImiKkVLg"],
  "Munich": ["HCUcZNGZo6k"],
  "Narita": ["KDwggKHQmrE"],
  "Nashville": ["AE9_rQ6vNCo"],
  "New Orleans": ["A14iV1uVSSg"],
  "New Taipei City": ["yyttxJz1p4w"],
  "New York City": ["ALMAbe623ng"],
  "Niagara Falls": ["phJRqNNj-eg"],
  "Nice": ["8iPOnMrk-YQ"],
  "Nizhny Novgorod": ["7PGHA50NLtY"],
  "Novosibirsk": ["CjvC-RY1z7o"],
  "Orlando": ["Ke8H5iWsJAo"],
  "Oslo": ["9hOpebXyreI"],
  "Palm Beach": ["jaAcRRBKIKs"],
  "Paris": ["WHNNHAoaZD4"],
  "Philadelphia": ["Q7Tg8sBJQpU"],
  "Phoenix": ["mCqdQZaQemI"],
  "Pittsburgh": ["L7j5Eawqt_s"],
  "Porto Alegre": ["ObLLYFQydV0"],
  "Prague": ["UALyXNioimI"],
  "Presidente Prudente": ["vtkFEuiLNdQ"],
  "Puebla": ["2rltaAPDbrg"],
  "Pune": ["SCeSlwJxRKU"],
  "Qatar": ["BhYko9wKOp0"],
  "Querétaro": ["V6crAKCNjLo"],
  "Recife": ["HJBuHhKBNlg"],
  "Rio De Janeiro": ["-EeboDkZp_g"],
  "Rome": ["8IDZKEc0Wgk"],
  "Salvador": ["n7A18QLPdHs"],
  "Samarkand": ["37lGuje4hfs"],
  "San Diego": ["8zstwGDSV1g"],
  "San Fernando, Pampanga": ["3csDImwaZGM"],
  "San Francisco": ["oLdr80iDFsc"],
  "Sanliurfa": ["WK6uBEZj_yU"],
  "Santiago de los Caballeros": ["SkxauBMrGb0"],
  "Santo Domingo": ["pQAqIoiUY_4"],
  "Seattle": ["iy8_7osp3Lo"],
  "Seoul": ["ckfOIEx8yqU"],
  "Singapore": ["aaGJ_fDcceg"],
  "Sofia": ["ctpOAWZqtQg"],
  "St. Petersburg": ["SUff9wXxlfE"],
  "Stockholm": ["dMR5UfFYqlg"],
  "Stuttgart": ["cXorznac5Wk"],
  "Sydney": ["he-d9OoiAnY"],
  "Taipei": ["-IA8PFxbBW8"],
  "Tampa": ["4g_14feyS6s"],
  "Tashkent": ["fz6rXEXk-Wg"],
  "Tehran": ["7DkoPGGdKAA"],
  "Tel Aviv": ["rkupHf87wtc"],
  "Thessaloniki": ["mdRHJLGOVsE"],
  "Tokyo": ["X2aY-HgWjzg"],
  "Toronto": ["Wq_IygQCtm8"],
  "Trabzon": ["hGk2LxB4d60"],
  "Vancouver": ["WbfjRoQVZSw"],
  "Vienna": ["_8D2ukmn0cs"],
  "Warsaw": ["ytBWLJrIrOQ"],
  "Washington DC": ["IkEvjdLCUck"],
  "Wuhan": ["wyG8eeSUd3M"],
  "Yekaterinburg": ["I46IZ1QsUdM"],
  "Zurich": ["4XceEfga_Fo"]
};
